name: voice_expense_tracker
description: A voice assistant with local storage for expense tracking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_tts: ^3.8.3
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  permission_handler: ^11.0.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true